/*
 * File: app/controller/subject/SubjectsController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.controller.subject.SubjectsController', {
    extend: 'Ext.app.Controller',

    selectedIndex: '0',
    models: [
        'subject.SubjectsModel'
    ],
    stores: [
        'subject.SubjectStore'
    ],
    views: [
        'MainPanel',
        'subject.SubjectsGridPanel',
        'subject.SubjectsForm',
        'subject.SubjectsPanel'
    ],

    refs: [
        {
            ref: 'subjectsForm',
            selector: 'form'
        }
    ],

    constructor: function(cfg) {
        cfg = cfg || {};
        this.callParent(this.processSubjectSubjectsController(cfg));
    },

    processSubjectSubjectsController: function(config) {
        return config;
    },

    onSubjectsgridSelect: function(rowmodel, record, index, eOpts) {
        window.console.log( "selected row in grid." );
        window.console.log( "index=" + index );
        //debugger;
        //if ( record ) {
        //    this.getSubjectsForm().getForm().loadRecord(record);
        //}
        this.selectedIndex = index;
    },

    onSubjectdescriptiontextareaChange: function(field, newValue, oldValue, eOpts) {
        // NEED TO MARK THE GRID's RECORD DIRTY HERE BUT I DON'T HOW TO GET A HOLD OF THE RECORD INDEX OR THE RECORD.
        window.console.log( 'selectedIndex=' + this.selectedIndex );
        window.console.log( "onSubjectdescriptiontextareraChange() field=" + field );
        var mystore = Ext.getStore("subject.SubjectStore");
        var myrecord = mystore.getAt( this.selectedIndex );
        myrecord.set( 'description', newValue );


    },

    onSubjectobjectivetextareaChange: function(field, newValue, oldValue, eOpts) {
        // NEED TO MARK THE GRID's RECORD DIRTY HERE BUT I DON'T HOW TO GET A HOLD OF THE RECORD INDEX OR THE RECORD.
        window.console.log( 'selectedIndex=' + this.selectedIndex );
        window.console.log( "onSubjectobjectivetextareraChange() field=" + field );
        var mystore = Ext.getStore("subject.SubjectStore");
        var myrecord = mystore.getAt( this.selectedIndex );
        myrecord.set( 'objectives', newValue );
    },

    onTooldeletestudentsbysubjectClick: function(tool, e, eOpts) {
        window.console.log( 'Delete' );
    },

    onToolnewsubjectsClick: function(tool, e, eOpts) {
        //debugger;
        window.console.log( 'New' );
        var newDialog = Ext.create( 'MySchool.view.subject.NewForm' );
        //window.console.log( "DEBUG" );
        //newDialog.show();
        newDialog.render( Ext.getBody() );
        newDialog.show();
    },

    onToolsearchsubjectsClick: function(tool, e, eOpts) {
        window.console.log( 'Search' );
    },

    onToolrefreshsubjectsClick: function(tool, e, eOpts) {
        // Add refresh handler code here.  Use example from chapter 2 of book.
        //debugger;
        window.console.log( 'Refresh' );
        var mystore = Ext.getStore("subject.SubjectStore");
        mystore.reload();
        //pnl.setTitle( 'Denis' );
    },

    onNewsubjectsubmitClick: function(button, e, eOpts) {
        //debugger;
        //var mystore = this.getSubjectStoreStore();
        window.console.log( "Submit New Subject" );
        var mystore = Ext.getStore("subject.SubjectStore");
        var myqtrstore = Ext.getStore( "subject.QuarterNameStore" );
        var myrecords = myqtrstore.getRange( 0, 3 );
        for( var i = 0; i < 4; i++ )
        {
            window.console.log( "qtrName=" + myrecords[i].get( 'qtrName' ) );
        }
        var myForm = button.up().getForm();
        myForm.reset();
        button.up().hide();
    },

    onNewsubjectcancelClick: function(button, e, eOpts) {
        //debugger;
        window.console.log( "Cancel New Subject" );
        var myForm = button.up().getForm();
        myForm.reset();
        button.up().hide();
    },

    init: function(application) {

        this.control({
            'subjectsgridpanel': {
                selectionchange: this.gridSelectionChange,
                viewready: this.onViewReady
            },
            'subjectsavetool': {
                click: this.onSubjectsavetoolidClick
            }
        });


        this.control({
            "#subjectsgrid": {
                select: this.onSubjectsgridSelect
            },
            "#subjectdescriptiontextarea": {
                change: this.onSubjectdescriptiontextareaChange
            },
            "#subjectobjectivetextarea": {
                change: this.onSubjectobjectivetextareaChange
            },
            "#tooldeletestudentsbysubject": {
                click: this.onTooldeletestudentsbysubjectClick
            },
            "#toolnewsubjects": {
                click: this.onToolnewsubjectsClick
            },
            "#toolsearchsubjects": {
                click: this.onToolsearchsubjectsClick
            },
            "#toolrefreshsubjects": {
                click: this.onToolrefreshsubjectsClick
            },
            "#newsubjectsubmit": {
                click: this.onNewsubjectsubmitClick
            },
            "#newsubjectcancel": {
                click: this.onNewsubjectcancelClick
            }
        });
    },

    onViewReady: function(grid) {

        grid.getSelectionModel().select( 0 );
    },

    onSubjectsavetoolidClick: function(tool, e, eOpts) {
        window.console.log( "Save" );
        //debugger;

        var mystore = Ext.getStore("subject.SubjectStore");

        var records = mystore.getModifiedRecords();
        for( var i = 0; i < records.length; i++ )
        {
            records[i].set( 'lastUpdated', new Date() );
            var form = this.getSubjectsForm().getForm();
            var formValues = form.getValues();
            records[i].set( 'description', formValues.description );
            records[i].set( 'objectives', formValues.objectives );
            window.console.log( 'objectives=' + formValues.objectives );
            window.console.log( 'description=' + formValues.description );
        }

        mystore.sync();

    },

    gridSelectionChange: function(model, records) {
        //debugger;
        if ( records[0] ) {
            this.getSubjectsForm().getForm().loadRecord(records[0]);
        }
    }

});
