// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.myschool.model;

import com.app.myschool.model.PreviousTranscripts;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect PreviousTranscripts_Roo_Json {
    
    public String PreviousTranscripts.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static PreviousTranscripts PreviousTranscripts.fromJsonToPreviousTranscripts(String json) {
        return new JSONDeserializer<PreviousTranscripts>().use(null, PreviousTranscripts.class).deserialize(json);
    }
    
    public static String PreviousTranscripts.toJsonArray(Collection<PreviousTranscripts> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<PreviousTranscripts> PreviousTranscripts.fromJsonArrayToPreviousTranscriptses(String json) {
        return new JSONDeserializer<List<PreviousTranscripts>>().use(null, ArrayList.class).use("values", PreviousTranscripts.class).deserialize(json);
    }
    
}
