// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.myschool.model;

import com.app.myschool.model.PreviousTranscripts;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PreviousTranscripts_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager PreviousTranscripts.entityManager;
    
    public static final List<String> PreviousTranscripts.fieldNames4OrderClauseFilter = java.util.Arrays.asList("type", "pdfURL", "comments", "student", "school", "createdDate");
    
    public static final EntityManager PreviousTranscripts.entityManager() {
        EntityManager em = new PreviousTranscripts().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long PreviousTranscripts.countPreviousTranscriptses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM PreviousTranscripts o", Long.class).getSingleResult();
    }
    
    public static List<PreviousTranscripts> PreviousTranscripts.findAllPreviousTranscriptses() {
        return entityManager().createQuery("SELECT o FROM PreviousTranscripts o", PreviousTranscripts.class).getResultList();
    }
    
    public static List<PreviousTranscripts> PreviousTranscripts.findAllPreviousTranscriptses(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM PreviousTranscripts o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, PreviousTranscripts.class).getResultList();
    }
    
    public static PreviousTranscripts PreviousTranscripts.findPreviousTranscripts(Long id) {
        if (id == null) return null;
        return entityManager().find(PreviousTranscripts.class, id);
    }
    
    public static List<PreviousTranscripts> PreviousTranscripts.findPreviousTranscriptsEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM PreviousTranscripts o", PreviousTranscripts.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<PreviousTranscripts> PreviousTranscripts.findPreviousTranscriptsEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM PreviousTranscripts o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, PreviousTranscripts.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void PreviousTranscripts.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void PreviousTranscripts.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            PreviousTranscripts attached = PreviousTranscripts.findPreviousTranscripts(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void PreviousTranscripts.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void PreviousTranscripts.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public PreviousTranscripts PreviousTranscripts.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        PreviousTranscripts merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
