// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.myschool.model;

import com.app.myschool.model.PreviousTranscripts;
import com.app.myschool.model.School;
import com.app.myschool.model.Student;
import java.util.Date;

privileged aspect PreviousTranscripts_Roo_JavaBean {
    
    public String PreviousTranscripts.getName() {
        return this.name;
    }
    
    public void PreviousTranscripts.setName(String name) {
        this.name = name;
    }
    
    public int PreviousTranscripts.getType() {
        return this.type;
    }
    
    public void PreviousTranscripts.setType(int type) {
        this.type = type;
    }
    
    public Boolean PreviousTranscripts.getOfficial() {
        return this.official;
    }
    
    public void PreviousTranscripts.setOfficial(Boolean official) {
        this.official = official;
    }
    
    public String PreviousTranscripts.getPdfURL() {
        return this.pdfURL;
    }
    
    public void PreviousTranscripts.setPdfURL(String pdfURL) {
        this.pdfURL = pdfURL;
    }
    
    public String PreviousTranscripts.getComments() {
        return this.comments;
    }
    
    public void PreviousTranscripts.setComments(String comments) {
        this.comments = comments;
    }
    
    public int PreviousTranscripts.getGradingScale() {
        return this.gradingScale;
    }
    
    public void PreviousTranscripts.setGradingScale(int gradingScale) {
        this.gradingScale = gradingScale;
    }
    
    public Student PreviousTranscripts.getStudent() {
        return this.student;
    }
    
    public void PreviousTranscripts.setStudent(Student student) {
        this.student = student;
    }
    
    public School PreviousTranscripts.getSchool() {
        return this.school;
    }
    
    public void PreviousTranscripts.setSchool(School school) {
        this.school = school;
    }
    
    public String PreviousTranscripts.getWhoUpdated() {
        return this.whoUpdated;
    }
    
    public void PreviousTranscripts.setWhoUpdated(String whoUpdated) {
        this.whoUpdated = whoUpdated;
    }
    
    public Date PreviousTranscripts.getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void PreviousTranscripts.setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    
    public Date PreviousTranscripts.getCreatedDate() {
        return this.createdDate;
    }
    
    public void PreviousTranscripts.setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
}
