/*
 * File: app/view/subject/SubjectsGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.subject.SubjectsGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.subjectsgridpanel',

    requires: [
        'Ext.grid.plugin.CellEditing'
    ],

    itemId: 'subjectsgrid',
    width: 1000,
    autoScroll: true,
    title: '[student name] Subjects',
    forceFit: true,
    store: 'subject.SubjectStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id',
                    text: 'subjectid',
                    format: '000000'
                },
                {
                    xtype: 'gridcolumn',
                    width: 94,
                    dataIndex: 'subjName',
                    text: 'Subject Name'
                },
                {
                    xtype: 'numbercolumn',
                    width: 97,
                    dataIndex: 'subjGradeLevel',
                    text: 'Grade Level',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'subjCreditHours',
                    text: 'Credit Hours'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'subjLastUpdated',
                    text: 'Date',
                    format: 'm/d/Y'
                },
                {
                    xtype: 'checkcolumn',
                    dataIndex: 'subjCompleted',
                    text: 'Complete?',
                    editor: {
                        xtype: 'checkboxfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'subjVersion',
                    text: 'version'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'qtrName',
                    text: 'Quarter'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'qtrYear',
                    text: 'QtrYear'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'studentName',
                    text: 'UserName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'qtrGrade',
                    text: 'Grade',
                    editor: {
                        xtype: 'numberfield'
                    }
                }
            ],
            viewConfig: {
                id: 'subjectsgridview'
            },
            plugins: [
                Ext.create('Ext.grid.plugin.CellEditing', {
                    clicksToEdit: 1
                })
            ]
        });

        me.callParent(arguments);
    }

});