/*
 * File: app/view/subject/NewForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.subject.NewForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newsubjectform',

    autoRender: false,
    draggable: true,
    floating: true,
    frame: true,
    height: 400,
    itemId: 'newsubjectform',
    width: 500,
    title: 'New Subject',
    url: 'quarters',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'quarters'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'My Fields',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Name'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Grade Level'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Credit Hours'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Description'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Objective'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Quarter'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    text: 'Cancel',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    text: 'Submit',
                    listeners: {
                        click: {
                            fn: me.onButtonClick1,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        //debugger;
        //var myform = this;
        this.getForm().reset();
        this.hide();

    },

    onButtonClick1: function(button, e, eOpts) {
        // In a real application, this would submit the form to the configured url
        // this.up('form').getForm().submit();
        this.getForm().reset();
        this.hide();
        Ext.MessageBox.alert('Thank you!', 'Your record has been submitted.');

    }

});