/*
 * File: app/view/subject/NewForm.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.subject.NewForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newsubjectform',

    requires: [
        'MySchool.view.subject.GradeTypeComboBox',
        'MySchool.view.subject.QuarterNamesComboBox'
    ],

    draggable: true,
    floating: true,
    frame: true,
    height: 490,
    itemId: 'newsubjectform',
    width: 500,
    title: 'New Subject',
    jsonSubmit: true,

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            jsonSubmit: true
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'My Fields',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Student User Name',
                            name: 'studentName',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Subject Name',
                            name: 'subjName'
                        },
                        {
                            xtype: 'gradetypecombobox',
                            anchor: '100%'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Grade Level',
                            name: 'subjGradeLevel'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Credit Hours',
                            name: 'subjCreditHours'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Description',
                            name: 'subjDescription'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Objectives',
                            name: 'subjObjectives'
                        },
                        {
                            xtype: 'quarternamescombobox',
                            anchor: '100%'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Quarter Year',
                            name: 'qtrYear'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    itemId: 'newsubjectcancel',
                    text: 'Cancel'
                },
                {
                    xtype: 'button',
                    itemId: 'newsubjectsubmit',
                    text: 'Submit'
                }
            ]
        });

        me.callParent(arguments);
    }

});