/*
 * File: app/store/monthly/EvaluationRatingsStore.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.store.monthly.EvaluationRatingsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MySchool.model.monthly.EvaluationRatings',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MySchool.model.monthly.EvaluationRatings',
            storeId: 'monthly.EvaluationRatingsStore',
            proxy: {
                type: 'rest',
                url: 'monthlyevaluationratingses',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});