// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.myschool.model;

import com.app.myschool.model.Grades;
import com.app.myschool.model.GradesDataOnDemand;
import com.app.myschool.model.GradesIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GradesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GradesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GradesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GradesIntegrationTest: @Transactional;
    
    @Autowired
    private GradesDataOnDemand GradesIntegrationTest.dod;
    
    @Test
    public void GradesIntegrationTest.testCountGradeses() {
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", dod.getRandomGrades());
        long count = Grades.countGradeses();
        Assert.assertTrue("Counter for 'Grades' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GradesIntegrationTest.testFindGrades() {
        Grades obj = dod.getRandomGrades();
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Grades' failed to provide an identifier", id);
        obj = Grades.findGrades(id);
        Assert.assertNotNull("Find method for 'Grades' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Grades' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GradesIntegrationTest.testFindAllGradeses() {
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", dod.getRandomGrades());
        long count = Grades.countGradeses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Grades', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Grades> result = Grades.findAllGradeses();
        Assert.assertNotNull("Find all method for 'Grades' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Grades' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GradesIntegrationTest.testFindGradesEntries() {
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", dod.getRandomGrades());
        long count = Grades.countGradeses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Grades> result = Grades.findGradesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Grades' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Grades' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GradesIntegrationTest.testFlush() {
        Grades obj = dod.getRandomGrades();
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Grades' failed to provide an identifier", id);
        obj = Grades.findGrades(id);
        Assert.assertNotNull("Find method for 'Grades' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGrades(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Grades' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GradesIntegrationTest.testMergeUpdate() {
        Grades obj = dod.getRandomGrades();
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Grades' failed to provide an identifier", id);
        obj = Grades.findGrades(id);
        boolean modified =  dod.modifyGrades(obj);
        Integer currentVersion = obj.getVersion();
        Grades merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Grades' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GradesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", dod.getRandomGrades());
        Grades obj = dod.getNewTransientGrades(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Grades' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Grades' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Grades' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GradesIntegrationTest.testRemove() {
        Grades obj = dod.getRandomGrades();
        Assert.assertNotNull("Data on demand for 'Grades' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Grades' failed to provide an identifier", id);
        obj = Grades.findGrades(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Grades' with identifier '" + id + "'", Grades.findGrades(id));
    }
    
}
