// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.myschool.model;

import com.app.myschool.model.QuarterNames;
import com.app.myschool.model.QuarterNamesDataOnDemand;
import com.app.myschool.model.QuarterNamesIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuarterNamesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuarterNamesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuarterNamesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuarterNamesIntegrationTest: @Transactional;
    
    @Autowired
    private QuarterNamesDataOnDemand QuarterNamesIntegrationTest.dod;
    
    @Test
    public void QuarterNamesIntegrationTest.testCountQuarterNameses() {
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", dod.getRandomQuarterNames());
        long count = QuarterNames.countQuarterNameses();
        Assert.assertTrue("Counter for 'QuarterNames' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuarterNamesIntegrationTest.testFindQuarterNames() {
        QuarterNames obj = dod.getRandomQuarterNames();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to provide an identifier", id);
        obj = QuarterNames.findQuarterNames(id);
        Assert.assertNotNull("Find method for 'QuarterNames' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuarterNames' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuarterNamesIntegrationTest.testFindAllQuarterNameses() {
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", dod.getRandomQuarterNames());
        long count = QuarterNames.countQuarterNameses();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuarterNames', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuarterNames> result = QuarterNames.findAllQuarterNameses();
        Assert.assertNotNull("Find all method for 'QuarterNames' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuarterNames' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuarterNamesIntegrationTest.testFindQuarterNamesEntries() {
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", dod.getRandomQuarterNames());
        long count = QuarterNames.countQuarterNameses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuarterNames> result = QuarterNames.findQuarterNamesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuarterNames' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuarterNames' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuarterNamesIntegrationTest.testFlush() {
        QuarterNames obj = dod.getRandomQuarterNames();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to provide an identifier", id);
        obj = QuarterNames.findQuarterNames(id);
        Assert.assertNotNull("Find method for 'QuarterNames' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuarterNames(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuarterNames' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuarterNamesIntegrationTest.testMergeUpdate() {
        QuarterNames obj = dod.getRandomQuarterNames();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to provide an identifier", id);
        obj = QuarterNames.findQuarterNames(id);
        boolean modified =  dod.modifyQuarterNames(obj);
        Integer currentVersion = obj.getVersion();
        QuarterNames merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuarterNames' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuarterNamesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", dod.getRandomQuarterNames());
        QuarterNames obj = dod.getNewTransientQuarterNames(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuarterNames' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuarterNames' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuarterNamesIntegrationTest.testRemove() {
        QuarterNames obj = dod.getRandomQuarterNames();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuarterNames' failed to provide an identifier", id);
        obj = QuarterNames.findQuarterNames(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuarterNames' with identifier '" + id + "'", QuarterNames.findQuarterNames(id));
    }
    
}
