/*
 * File: app/view/monthly/NewSummaryFormPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.monthly.NewSummaryFormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.monthlynewsummaryformpanel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.Number',
        'Ext.form.field.Hidden',
        'Ext.button.Button'
    ],

    draggable: true,
    floating: true,
    frame: true,
    itemId: 'monthlynewsummaryformpanel',
    bodyPadding: 10,
    title: 'New Monthly Summary Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    itemId: 'monthlysummaryfieldset',
                    title: 'Monthly Summary Fields',
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-dsubject',
                            fieldLabel: 'Subject',
                            name: 'dsubject'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-dquarter',
                            fieldLabel: 'Quarter',
                            name: 'dquarter'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-dyear',
                            fieldLabel: 'Year',
                            name: 'dyear'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-month_number',
                            fieldLabel: 'Month Number(1-12)',
                            name: 'month_number',
                            validateBlank: true,
                            maxValue: 12,
                            minValue: 1
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-feelings',
                            fieldLabel: 'feelings',
                            name: 'feelings',
                            value: 'feelings'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-reflections',
                            fieldLabel: 'reflections',
                            name: 'reflections',
                            value: 'reflections'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-patternsofcorrections',
                            fieldLabel: 'patterns of correctons',
                            name: 'patternsofcorrections',
                            value: 'patterns of corrections'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-effectivenessofactions',
                            fieldLabel: 'effectivenes of actions',
                            name: 'effectivenessofactions',
                            value: 'effectiveness of actions'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-actionresults',
                            fieldLabel: 'action results',
                            name: 'actionresults',
                            value: 'action results'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-realizations',
                            fieldLabel: 'realizations',
                            name: 'realizations',
                            value: 'realizations'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-plannedchanges',
                            fieldLabel: 'planned changes',
                            name: 'plannedchanges',
                            value: 'planned changes'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-comments',
                            fieldLabel: 'comments',
                            name: 'comments',
                            value: 'comments'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-subjectid',
                            fieldLabel: 'subjectId',
                            name: 'subjectId'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-quarterid',
                            fieldLabel: 'quarterid',
                            name: 'quarterId'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-studentname',
                            fieldLabel: 'studentname',
                            name: 'studentname'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-subjectname',
                            fieldLabel: 'subjectname',
                            name: 'subjectname'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-studentid',
                            fieldLabel: 'studentid',
                            name: 'studentId'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-subject',
                            fieldLabel: 'subject',
                            name: 'subject'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-quarter',
                            fieldLabel: 'quarter',
                            name: 'quarter'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'newmonthlysummary-year',
                            fieldLabel: 'year',
                            name: 'year'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    itemId: 'newmonthlysummarycanel',
                    text: 'Canel'
                },
                {
                    xtype: 'button',
                    itemId: 'newmonthlysummarysubmit',
                    text: 'Submit'
                }
            ]
        });

        me.callParent(arguments);
    }

});