/*
 * File: app/view/weekly/skills/GridPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.weekly.skills.GridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.weeklyskillsgridpanel',

    requires: [
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.grid.column.Boolean'
    ],

    id: 'weeklyskillsgridpanel',
    itemId: 'weeklydetailsgridpanel',
    width: 963,
    autoScroll: true,
    title: '[student name]Weekly Skills By Subject And Week',
    forceFit: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'subject_name',
                    text: 'Subject Name'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'year',
                    text: 'Year'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'month',
                    text: 'Month'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'week',
                    text: 'Week'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Remembering'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Understanding'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Applying'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Analyzing'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Evaluating'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Creating'
                },
                {
                    xtype: 'booleancolumn',
                    text: 'Locked?'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'student_id',
                    text: 'idstudent'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    text: 'idsubject'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    text: 'idweekly'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    text: 'idskill'
                }
            ],
            viewConfig: {
                id: 'weeklyskillsgridview'
            }
        });

        me.callParent(arguments);
    }

});