/*
 * File: app/view/monthly/summary/DetailsGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.monthly.summary.DetailsGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.monthlydetailsgridpanel',

    requires: [
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.grid.column.Boolean'
    ],

    height: 373,
    itemId: 'monthlysummarygridpanel',
    width: 150,
    title: '[student name]',
    forceFit: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'year',
                    text: 'Year'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'month',
                    text: 'Month'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'student_id',
                    text: 'idstudent'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    text: 'idmonthly_summary_ratings'
                },
                {
                    xtype: 'booleancolumn',
                    text: 'Locked?'
                }
            ],
            viewConfig: {
                id: 'monthlysummarygridview'
            }
        });

        me.callParent(arguments);
    }

});