/*
 * File: app/store/subject/SubjectStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.store.subject.SubjectStore', {
    extend: 'Ext.data.Store',
    alias: 'store.subjectstore',

    requires: [
        'MySchool.model.subject.SubjectsModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MySchool.model.subject.SubjectsModel',
            storeId: 'SubjectStore',
            proxy: {
                type: 'rest',
                url: 'subjects/json',
                headers: {
                    Accept: 'application/json'
                },
                reader: {
                    type: 'json',
                    root: 'data'
                },
                writer: {
                    type: 'json',
                    encode: true,
                    root: 'data'
                },
                listeners: {
                    exception: {
                        fn: me.onRestException,
                        scope: me
                    }
                }
            },
            listeners: {
                beforesync: {
                    fn: me.onJsonstoreBeforeSync,
                    scope: me
                },
                write: {
                    fn: me.onJsonstoreWrite,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onRestException: function(proxy, response, operation, eOpts) {
        //debugger;
        var smsg = response.request.options.method + ':' + response.request.options.action + ':' + response.responseText + ':' + response.status + ':' + response.statusText + ':' + operation.params.data; 
        Ext.MessageBox.show({
            title: 'REMOTE EXCEPTION', 
            msg: smsg,
            icon: Ext.MessageBox.ERROR,
            buttons: Ext.Msg.OK
        });
        window.console.log( smsg );
    },

    onJsonstoreBeforeSync: function(options, eOpts) {
        //debugger;
        var smsg = 'Before sync()'; 
        //Ext.MessageBox.show({
        //    title: 'REMOTE EXCEPTION', 
        //    msg: smsg,
        //    icon: Ext.MessageBox.ERROR,
        //    buttons: Ext.Msg.OK
        //});
        window.console.log( smsg );
    },

    onJsonstoreWrite: function(store, operation, eOpts) {
        store.reload();
    }

});