/*
 * File: app/view/grade/GridPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.grade.GridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.gradegridpanel',

    requires: [
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.grid.column.Boolean'
    ],

    id: 'gradesgridpanel',
    itemId: 'gradesgridpanel',
    minHeight: 700,
    width: 150,
    forceFit: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    text: 'Quarter'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'subject_name',
                    text: 'Subject Name'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Grade'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    text: 'Locked?'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    text: 'idsubject'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    text: 'idquarter'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    text: 'idstudent'
                }
            ],
            viewConfig: {
                id: 'gradesgridview'
            }
        });

        me.callParent(arguments);
    }

});