/*
 * File: app/model/SubjectsModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.SubjectsModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'gradeLevel',
            type: 'int'
        },
        {
            name: 'creditHours',
            type: 'int'
        },
        {
            name: 'completed',
            type: 'boolean'
        },
        {
            name: 'whoUpdated',
            type: 'string'
        },
        {
            dateFormat: 'm/d/Y',
            name: 'lastUpdated',
            type: 'date'
        },
        {
            name: 'description',
            type: 'string'
        },
        {
            name: 'objectives',
            type: 'string'
        },
        {
            name: 'version',
            type: 'string'
        }
    ]
});