/*
 * File: app/view/student/ProfileGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.student.ProfileGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.studentprofilegridpanel',

    requires: [
        'Ext.grid.column.Number',
        'Ext.grid.column.Boolean',
        'Ext.grid.View'
    ],

    itemId: 'studentprofilegridpanel',
    minHeight: 150,
    autoScroll: true,
    title: '[faculty name]Students',
    columnLines: true,
    forceFit: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'idstudent',
                    text: 'idstudent'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'firstname',
                    text: 'First Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'middlename',
                    text: 'Middle Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'lastname',
                    text: 'Last Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'email',
                    text: 'Email'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'locked',
                    text: 'Locked?'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'idfaculty',
                    text: 'idfaculty'
                }
            ],
            viewConfig: {
                maxHeight: 100
            }
        });

        me.callParent(arguments);
    }

});