// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.myschool.web;

import com.app.myschool.model.PreviousTranscripts;
import com.app.myschool.web.PreviousTranscriptsController;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

privileged aspect PreviousTranscriptsController_Roo_Controller_Json {
    
    @RequestMapping(params = "find=ByNameEquals", headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> PreviousTranscriptsController.jsonFindPreviousTranscriptsesByNameEquals(@RequestParam("name") String name) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        return new ResponseEntity<String>(PreviousTranscripts.toJsonArray(PreviousTranscripts.findPreviousTranscriptsesByNameEquals(name).getResultList()), headers, HttpStatus.OK);
    }
    
    @RequestMapping(params = "find=ByPdfURLEquals", headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> PreviousTranscriptsController.jsonFindPreviousTranscriptsesByPdfURLEquals(@RequestParam("pdfURL") String pdfURL) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        return new ResponseEntity<String>(PreviousTranscripts.toJsonArray(PreviousTranscripts.findPreviousTranscriptsesByPdfURLEquals(pdfURL).getResultList()), headers, HttpStatus.OK);
    }
    
}
