/*
 * File: app/view/SubjectsPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.SubjectsPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.subjectspanel',

    requires: [
        'MySchool.view.SubjectsGridPanel',
        'MySchool.view.SubjectsForm'
    ],

    id: 'subjectspanel',
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: 'Subjects By Student',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'subjectsgridpanel',
                    flex: 1
                },
                {
                    xtype: 'subjectsform',
                    flex: 1
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        // Add refresh handler code here.  Use example from chapter 2 of book.
                        //debugger;

                        var pnl = this.up('subjectspanel').down('subjectsgridpanel');
                        var store = pnl.getStore();
                        store.reload();
                        //pnl.setTitle( 'Denis' );

                    },
                    id: 'toolrefreshstudentsbysubject',
                    tooltip: 'Refresh',
                    type: 'refresh'
                },
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        // add search handler code here.
                    },
                    id: 'toolsearchstudentsbysubject',
                    tooltip: 'Search',
                    type: 'search'
                },
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        // add new/insert handler code here.
                    },
                    id: 'toolnewstudentsbysubject',
                    tooltip: 'New',
                    type: 'plus'
                },
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        // Add save/udate handler code here.
                        debugger;
                        window.console.log('SAVE...' );
                        //var subjectsModel = Ext.ModelManager.getModel( 'MySchool.model.SubjectsModel' );
                        //subjectsModel.set( 'lastUpdated', new Date() );
                        //subjectsModel.save({
                        //    success: function() {
                        //        console.log( 'The subject was updated' );
                        //    }
                        //});
                        //var pnl = this.up('subjectspanel').down('subjectsgridpanel');
                        //var mystore = pnl.getStore();
                        //var sm = pnl.getModel();
                        ////sm.set( 'lastUpdated', new Date() );
                        //sm.save({
                        //    success: function() {
                        //        console.log( 'The subject was updated' );
                        //    }
                        //});


                        var pnl = this.up('subjectspanel').down('subjectsgridpanel');
                        var mystore = pnl.getStore();
                        //var sm = pnl.getSelectionModel();
                        var records = mystore.getModifiedRecords();
                        for( var i = 0; i < records.length; i++ )
                        {
                            var index = mystore.indexOf( records[i] );
                            mystore.getAt( index ).set( 'lastUpdated', new Date() );
                            //    //mystore.getAt( index ).set( 'completed', 'false' );
                            records[i].set( 'lastUpdated', new Date() );
                            //    //records[i].set( 'completed', 'false' );
                            //    //records[i].save();
                            //    //store.sync();
                            //mystore.commitChanges();
                            //mystore.sync();
                            //    //store.save();
                            //    //store.commit();
                        }
                        mystore.sync();
                        mystore.commitChanges();
                        //store.each(function(record)  
                        //{  
                        //    record.set( 'lastUpdated', new Date() );
                        //    record.save();
                        //  //record.fields.each(function(field) 
                        //  //{ 
                        //  //  //var fieldValue = record.get(field.name);
                        //  //    record.set( 'lastUpdated', new Date() );
                        //  //}); 
                        //},this);
                        //store.sync();
                        //store.save();
                        //store.commitChanges();
                        //store.save();
                        //store.sync();
                        //pnl.setTitle( 'Denis' );
                    },
                    id: 'toolsavestudentsbysubject',
                    tooltip: 'Save',
                    type: 'save'
                },
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        // Add delete handler code here.
                    },
                    id: 'tooldeletestudentsbysubject',
                    tooltip: 'Delete',
                    type: 'minus'
                }
            ]
        });

        me.callParent(arguments);
    }

});