/*
 * File: app/view/SubjectDeleteTool.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.SubjectDeleteTool', {
    extend: 'Ext.panel.Tool',
    alias: 'widget.subjectdeletetool',

    id: 'tooldeletestudentsbysubject',
    tooltip: 'Delete',
    type: 'minus',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    },

    handler: function(event, toolEl, owner, tool) {
        // Add delete handler code here.
    }

});