/*
 * File: app/view/bodiesofwork/NewForm.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.bodiesofwork.NewForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newbodiesofworkform',

    requires: [
        'MySchool.view.common.QuarterSubjectComboBox',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    draggable: true,
    floating: true,
    frame: true,
    itemId: 'newbodiesofworkform',
    width: 500,
    title: 'New Body of work for Student',
    jsonSubmit: true,

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            jsonSubmit: true
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'My Fields',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'newbodiesofworkform-studentName',
                            fieldLabel: 'Student User Name',
                            name: 'studentUserName',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            itemId: 'newbodiesofworkform-workName',
                            fieldLabel: 'Work Name',
                            name: 'workName',
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'commonquartersubjectcombobox',
                            itemId: 'newbodiesofworkform-quarter'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            disabled: true,
                            itemId: 'newbodiesofworkform-what',
                            fieldLabel: 'What',
                            name: 'what',
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            disabled: true,
                            itemId: 'newbodiesofworkform-description',
                            fieldLabel: 'Description',
                            name: 'description',
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            disabled: true,
                            itemId: 'newbodiesofworkform-objective',
                            fieldLabel: 'Objective',
                            name: 'objective',
                            allowOnlyWhitespace: false
                        }
                    ]
                },
                {
                    xtype: 'button',
                    itemId: 'newbodiesofworkcancel',
                    text: 'Cancel'
                },
                {
                    xtype: 'button',
                    itemId: 'newbodiesofworksubmit',
                    text: 'Submit'
                },
                {
                    xtype: 'button',
                    itemId: 'newbodiesofworkcreate',
                    text: 'Create'
                }
            ]
        });

        me.callParent(arguments);
    }

});