/*
 * File: app/view/student/ProfileForm.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.student.ProfileForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.studentprofileform',

    requires: [
        'Ext.form.field.Text'
    ],

    itemId: 'studentprofileform',
    minHeight: 500,
    autoScroll: true,
    layout: 'vbox',
    bodyPadding: 10,
    collapseFirst: false,
    frameHeader: false,
    title: 'Student Profile Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'student-firstname',
                    width: 300,
                    fieldLabel: 'First Name'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-middlename',
                    width: 300,
                    fieldLabel: 'Middle Name'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-lastname',
                    width: 300,
                    fieldLabel: 'Last Name'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-mobile',
                    fieldLabel: 'Mobile Phone'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-phone',
                    fieldLabel: 'Phone'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-address1',
                    width: 300,
                    fieldLabel: 'Address1'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-address2',
                    width: 300,
                    fieldLabel: 'Address2'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-street',
                    width: 300,
                    fieldLabel: 'Street'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-city',
                    width: 300,
                    fieldLabel: 'City'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-province',
                    width: 300,
                    fieldLabel: 'Province/State'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-postalcode',
                    fieldLabel: 'Postal Code'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-country',
                    fieldLabel: 'Country'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-email',
                    width: 300,
                    fieldLabel: 'Email'
                },
                {
                    xtype: 'textfield',
                    itemId: 'student-facultyId',
                    fieldLabel: 'Faculty ID'
                }
            ]
        });

        me.callParent(arguments);
    }

});