/*
 * File: app/model/bodiesofwork/BodiesOfWorkModel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.model.bodiesofwork.BodiesOfWorkModel', {
    extend: 'Ext.data.Model',
    alias: 'model.bodiesofworkmodel',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'subjName',
            type: 'string'
        },
        {
            mapping: 'workName',
            name: 'name',
            type: 'string'
        },
        {
            name: 'description',
            type: 'string'
        },
        {
            name: 'what',
            type: 'string'
        },
        {
            name: 'objective',
            type: 'string'
        },
        {
            name: 'active',
            type: 'boolean'
        },
        {
            name: 'locked',
            type: 'boolean'
        },
        {
            name: 'completed',
            type: 'boolean'
        },
        {
            name: 'whoUpdated',
            type: 'string'
        },
        {
            dateFormat: 'd/m/Y',
            name: 'lastUpdated',
            type: 'date'
        },
        {
            name: 'subjGradeLevel',
            type: 'int'
        },
        {
            name: 'subjCreditHours',
            type: 'int'
        }
    ]
});