/*
 * File: app/view/daily/DetailsTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySchool.view.daily.DetailsTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.dailydetailstabpanel',

    requires: [
        'MySchool.view.daily.DailyHoursTabPanel',
        'MySchool.view.daily.ResourcesUsedTabPanel',
        'MySchool.view.daily.StudyDetailsTabPanel',
        'MySchool.view.daily.EvaluationsTabPanel',
        'MySchool.view.daily.CorrectionsTabPanel',
        'MySchool.view.daily.ActionsTabPanel',
        'Ext.panel.Panel',
        'Ext.tab.Tab'
    ],

    height: 300,
    itemId: 'bottomdailytabpanel',
    minHeight: 300,
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'dailyhourstabpanel'
                },
                {
                    xtype: 'dailyresourcesusedtabpanel'
                },
                {
                    xtype: 'dailystudydetailstabpanel'
                },
                {
                    xtype: 'dailyevaluationstabpanel'
                },
                {
                    xtype: 'dailycorrectionstabpanel'
                },
                {
                    xtype: 'dailyactionstabpanel'
                }
            ]
        });

        me.callParent(arguments);
    }

});